apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels: 
    app: web-app
  
spec:
  containers:
    - name: nginx-app
      image: areghagag/image
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80  
